# ???????????? http://localhost:8080?
server.port=8080

# MySQL ????????? 3306 ???? zijin_supply_chain ????
spring.datasource.url=jdbc:mysql://localhost:3307/zijin_supply_chain?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true

# MySQL ???????? root????? Navicat ???????
spring.datasource.username=root

# MySQL ????????????? MySQL ???????
spring.datasource.password=123456

# MySQL JDBC ????Spring Boot ????? MySQL?
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?? Spring Boot ??????? SQL ??????????? Navicat ???
spring.sql.init.mode=never

# ?? JSON ??????????
spring.jackson.time-zone=Asia/Shanghai

# ?????????
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss